name: test demo
on: [push]
jobs:
  my_job:
    runs-on: ubuntu-latest
    container: 
      image: maven:3-jdk-11
    defaults:
      run:
        working-directory: helloworldDemo
    steps:
      - name: file check
        run: ls
      - name: build
        run: mvn package
