name: test demo
on: [push]
jobs:
  my_job:
    runs-on: ubuntu-latest

        
    steps:
      - uses: actions/checkout@v2
        
      - name: build
        run: mvn package 
      - name: test run
        run: java -jar target/helloworldDemo-0.0.1.jar server hello_world.yml
